/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package corejava;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
            int a, b;
            a = 1 ; // it could be any number 
            b = 2 ; // same here
            System . out . println( a + b);
    } 
}
        
    
    

 