/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package corejava;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
            int a, b,c ;
            a = 2 ; 
            b = 3 ;
            c=5 ;
            int x=a+b+c;
            System . out . println(x);
    } 
}
        
    
    

 